# Generated by Django 5.0 on 2024-01-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_jsonserializer_api_jsonserializer_api'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
        migrations.DeleteModel(
            name='View',
        ),
        migrations.RemoveField(
            model_name='jsonserializer',
            name='api',
        ),
        migrations.AddField(
            model_name='api',
            name='serializers',
            field=models.ManyToManyField(blank=True, to='website.jsonserializer'),
        ),
        migrations.AlterField(
            model_name='api',
            name='content',
            field=models.TextField(blank=True, default="response_data['message'] = 'Default API response!'\nresponse_data['status_code'] = 200", max_length=2500, null=True),
        ),
    ]
