# Generated by Django 5.0 on 2024-01-09 08:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_file_delete_view_remove_jsonserializer_api_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='api',
            name='serializers',
        ),
        migrations.AlterField(
            model_name='api',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default="response_data['message'] = 'Default API response!'\nresponse_data['status_code'] = 200", null=True),
        ),
        migrations.AlterField(
            model_name='cascadestyle',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='javascript',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='jsonserializer',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='meta',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True),
        ),
    ]
