# Generated by Django 5.0 on 2024-01-09 08:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_remove_api_serializers_alter_api_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content',
            field=tinymce.models.HTMLField(default="response_data['message'] = 'Default API response!'\nresponse_data['status_code'] = 200"),
        ),
    ]
