# Generated by Django 5.0 on 2024-01-09 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_api_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='content',
            field=models.TextField(default="response_data['message'] = 'Default API response!'\nresponse_data['status_code'] = 200"),
        ),
    ]
