# Generated by Django 5.0 on 2024-01-09 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_javascript_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cascadestyle',
            name='content',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
