# Generated by Django 5.0 on 2024-01-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_remove_page_content_remove_page_header_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('base_header', models.TextField(blank=True, default='', null=True)),
                ('base_footer', models.TextField(blank=True, default='', null=True)),
                ('fav_icon', models.FileField(blank=True, null=True, upload_to='', verbose_name='website/favicon/')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='website.website'),
        ),
    ]
