# Generated by Django 5.0 on 2024-01-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_website_page_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='footer',
        ),
        migrations.RemoveField(
            model_name='page',
            name='header',
        ),
        migrations.AddField(
            model_name='page',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
