# Generated by Django 5.0 on 2024-01-14 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_remove_page_footer_remove_page_header_page_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='footer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='footer_widget', to='website.widget'),
        ),
        migrations.AddField(
            model_name='page',
            name='header',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='header_widget', to='website.widget'),
        ),
    ]
